import type { Metadata } from "next";
import { Inter, Karla } from "next/font/google";
import "./globals.css";
import ThemeRegistry from "@/theme/ThemeRegistry";
import { NextAuthProvider } from "@/auth/NextAuthProvider";

const karla = Karla({ subsets: ["latin"], variable: "--font-karla" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={karla.className}>
     
      <div className="absolute overflow-hidden -left-[15%] top-[5%] aspect-square h-[110%] bg-[radial-gradient(#5526ba35_0%,_transparent_70%)] dark:bg-[radial-gradient(#5526ba35_0%,_transparent_70%)]"></div>
      <div className="absolute  overflow-hidden -right-[15%]  -top-[25%] aspect-square h-[110%] bg-[radial-gradient(#156dcf45_0%,_transparent_70%)] dark:bg-[radial-gradient(#156dcf35_0%,_transparent_70%)]"></div>
        <ThemeRegistry options={{ key: "mui" }}>
          <NextAuthProvider>{children}</NextAuthProvider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
